### ISSUE TITLE
Wrong register in repository URL in PackageInfo.g

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/FPLSA#5]
It is not possible to check for package updates:
```
Package: FPLSA
# Error (/circa/home/gap-jenkins/pkgadmin/pkgcache/fplsa/tmp/tmpinfo.g): no pa\
ckage info bound!
  WARNING (FPLSA): no success in download of the current info file 
  from https://gap-packages.github.io/FPLSA/PackageInfo.g
```

This happens because the package name is in uppercase, and the repository - in lowercase.

In my packages, which have the same naming style, I use `LowercaseString(~.PackageName)`:
```
SourceRepository := rec(
    Type := "git",
    URL := Concatenation( "https://github.com/gap-packages/", LowercaseString(~.PackageName) ),
),
IssueTrackerURL := Concatenation( ~.SourceRepository.URL, "/issues" ),
PackageWWWHome  := Concatenation( "https://gap-packages.github.io/", LowercaseString(~.PackageName) ),
...
```

**Comment by fingolfin** [comment]
I renamed the repository, which should fix this this issue. It also means the URLs in the README are now off, but that's hopefully not as bad (the issue URL works anyway, due to an automatic redirect), and will be fixed in the next release.
